general:
  conv_mode: matrix
  enable_incomplete_verification: false
  root_path: ${CONFIG_PATH}
  csv_name: zubov_spec/two_machine.csv
model:
  name: >-
    Customized("../crown_verification/models.py", "create_two_machine_power")
  path: ${CONFIG_PATH}/../models/two_machine_new.pth
  input_shape: [-1, 2]
data:
  # Only used for computing the level set, not the final verification which uses the CSV file.
  # Use the box_data() loader in "lyapunov_models.py".
  # Scale is the factor of tbe verification box. Set scale = 1.0 by default. Reduce scale to make the problem easier.
  # hole_size must be 1.0 here, since we want to find the minimum on the boundary.
  dataset: Customized("models.py", "box_data", lower_limit=[-1,0, -1.5], upper_limit=[1.5, 1.0], ndim=2, scale=1.0, hole_size=1.0)
attack:
  pgd_order: before
  pgd_restarts: 10000
  pgd_steps: 1000
  pgd_alpha: 0.001
  pgd_alpha_scale: True
solver:
  batch_size: 500000
  min_batch_size_ratio: 0.
  bound_prop_method: crown
bab:
  override_timeout: 100000000
  decision_thresh: -1.e-6  # Tolerance. Must not be exact zero.
  branching:
    method: sb  # Can be "naive" or "sb". "sb" is usually better.
    input_split:
      enable: True
      ibp_enhancement: True
      compare_with_old_bounds: True
      adv_check: 0
      sb_coeff_thresh: 0.01  # Hyperparameter for "sb". Sometimes larger values like 0.01, 0.1 work better.
      enable_clip_domains: True
      reorder_bab: True
      show_progress: True
