run_dir: ./output/pendulum_state/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb_enabled: False 
wandb_entity: ??? 

load_lyaloss: examples/data/pendulum/state_feedback/lyaloss_init.pth
Vmin_x_pgd_path: null 
derivative_x_buffer_path: null 
